version: '2'

services:

    gunicorn:
      build: ./py/
      ports:
       - "8000:8000"

    node:
      build: ./js/
      ports:
       - "3000:3000"

    nginx:
        image: nginx:1.15.3
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - gunicorn
            - node

    graphite:
        image: graphiteapp/graphite-statsd:1.1.3
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        image: grafana/grafana:5.0.4
        ports:
            - "80:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: google/cadvisor:v0.27.4
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

    gunicorn_1:
      build: ./py/
      ports:
       - "8001:8000"

    gunicorn_2:
      build: ./py/
      ports:
       - "8002:8000"

    gunicorn_3:
      build: ./py/
      ports:
       - "8003:8000"

    node_1:
      build: ./js/
      ports:
       - "3001:3000"

    node_2:
      build: ./js/
      ports:
       - "3002:3000"

    node_3:
      build: ./js/
      ports:
       - "3003:3000"

volumes:
    grafana_config:
        driver: local
